### ISSUE TITLE
Extract the most relevant terms for every document (section content)

### ISSUE THREAD

**Issue by michelemostarda** [dbpedia/jsonpedia-extractor#4]
An inverted index already stores informations about terms frequency and relevance (see tf/idf vectors). From the Lucene programmatic API it is really easy to retrieve such information, try to extract the same from the Elasticsearch API. Otherwise we have to create a parallel Lucene index used only for retrieve such information.

**Comment by michelemostarda** [comment]
Try to verify if ElasticSearch exposes something through JMX http://en.wikipedia.org/wiki/Java_Management_Extensions

**Comment by gigaroby** [comment]
http://stackoverflow.com/questions/9189179/extract-tf-idf-vectors-with-lucene
